apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
        listen 80;

        location /api/ {
            proxy_pass http://backend-service:5000/api/;
            proxy_set_header Host $host;
        }

        location / {
            return 200 'Frontend - Accede a /api/status para probar el backend\n';
            add_header Content-Type text/plain;
        }
    }
