apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: database
  name: database
  namespace: ej3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - image: postgres:15
        name: postgres
        envFrom:
        - configMapRef:
            name: postgres-config
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: servicio-postgres
  name: servicio-postgres
  namespace: ej3
spec:
  ports:
  - name: puerto-porque-si
    port: 5432
    targetPort: 5432
  selector:
    app: database
  type: ClusterIP
